version: '3'

services:
    app:
        image: golang:1.14.1-alpine3.11
        container_name: go
        volumes:
            - ".:/go/src"
        ports:
            - "80:8080"
        working_dir: /go/src/codeeducation/
        command: go run main.go